### ISSUE TITLE
Not working for some tokens in my html string?

### ISSUE THREAD

**Issue by devendroid** [akshay-naik/TextHighlighter#8]
Seems library not working properly, I want to change the color of heading "History of C language" but it not changing:

**MyString:**
`<string name="test"><![CDATA[C is a structured programming language developed by Dennis Ritchie in 1973 at Bell Laboratories. It is one of the most popular computer languages today because of its structure, high-level abstraction, machine independent feature. C language was developed with UNIX operating system, so it is strongly associated with UNIX, which is one of the most popular network operating system in use today and heart of internet data superhighway.<br/><br/>History of C language<br/>C language has evolved from three different structured language ALGOL, BCPL and B Language. It uses many concepts from these languages and introduced many new concepts such as data types, struct, pointer. In 1988, the language was formalised by <strong>American National Standard Institute</strong>(ANSI). In 1990, a version of C language was approved by the <strong>International Standard Organisation</strong>(ISO) and that version of C is also referred to as C89]]></string>`

**Using Code:**
   ```
TextHighlighter highlighter = new TextHighlighter();
   highlighter.setColorForTheToken("History of C language","red");
   String highlightedText = highlighter.getHighlightedText(getString(R.string.test));
   txtView.setText(Html.fromHtml(highlightedText));
```

But not working its working for some of the token like "structured", "languages",...?
and not working for some of like "superhighway", "History of C language",....?

Can you let me know if I'm doing anything wrong Or fix the issue.

Thanks,

**Comment by nakshay** [comment]
@devsideal thanks for using TextHighlighter,

it seems like you are using a wrong method for setting the color, please refer a README file [https://github.com/nakshay/TextHighlighter](url) . To set a color for **one specific word** you should use highlighter.setColorForTheToken("word","color") and to set the color for **multiple words** you should use 
highlighter.setColorForTheToken("**arrayOfWords**","color").
In your case you are passing multiple words where single word is expected, you can create an array of string and then pass it to the method like below.
 `highlighter.setColorForTheToken(new String[]{"History", "of", "C"},"red");`
This will give highlighted text for all three words.

Second case you mentioned it is not working for words like superhighway because it has "." attached to it and hence will be passed as "superhighway." to the library  I am working on new update to the library [https://github.com/nakshay/TextHighlighter/wiki](url) which will remove these kind of issues, for now you can do a workaround by passing "." with the word  `superhighway.` instead of `superhighway`  while setting the color. 

Let me know if this solves your problem or any other issues you are facing , accordingly I will close the issue. Cheers ;)

**Comment by devendroid** [comment]
@nakshay thanks for reply, I got your points and fixed my issues.
